name: Deploy to Vercel

description: 'Builds and deploys a project to Vercel (supports both production and preview environments)'

inputs:
    vercel-token:
        description: 'Token to access Vercel'
        required: true
    environment:
        description: 'Vercel environment (production or preview)'
        required: true
        default: 'preview'
    build-args:
        description: 'Additional arguments for Vercel build command (e.g., --prod for production)'
        required: false
        default: ''
    deploy-args:
        description: 'Additional arguments for Vercel deploy command (e.g., --prod for production)'
        required: false
        default: ''

runs:
    using: "composite"
    steps:
        - name: Install Vercel CLI
          shell: bash
          run: |
              set -e
              npm i --global vercel

        - name: Pull environment variables from Vercel
          shell: bash
          run: |
              set -e
              if [ "${{ inputs.environment }}" = "production" ]; then
                  vercel pull --environment=production --token=${{ inputs.vercel-token }}
              else
                  vercel pull --environment=preview --token=${{ inputs.vercel-token }}
              fi

        - name: Build project locally
          shell: bash
          run: |
              set -e
              if [ -n "${{ inputs.build-args }}" ]; then
                  vercel build ${{ inputs.build-args }}
              else
                  vercel build
              fi

        - name: Deploy prebuilt project to Vercel
          shell: bash
          run: |
              set -e
              if [ -n "${{ inputs.deploy-args }}" ]; then
                  vercel deploy --prebuilt ${{ inputs.deploy-args }} --token=${{ inputs.vercel-token }}
              else
                  vercel deploy --prebuilt --token=${{ inputs.vercel-token }}
              fi
