name: Deploy to Vercel

description: 'Builds and deploys a project to Vercel (supports both production and preview environments)'

inputs:
    vercel-token:
        description: 'Token to access Vercel'
        required: true
    vercel-org-id:
        description: 'Vercel Organization ID'
        required: true
    vercel-project-id:
        description: 'Vercel Project ID'
        required: true
    environment:
        description: 'Vercel environment (production or preview)'
        required: true
        default: 'preview'
    build-args:
        description: 'Additional arguments for Vercel build command (e.g., --prod for production)'
        required: false
        default: ''
    deploy-args:
        description: 'Additional arguments for Vercel deploy command (e.g., --prod for production)'
        required: false
        default: ''

outputs:
    deployment-url:
        description: 'The URL of the deployed project'
        value: ${{ steps.deploy.outputs.url }}

runs:
    using: "composite"
    steps:
        - name: Install Vercel CLI
          shell: bash
          run: npm i --global vercel

        - name: Pull environment variables from Vercel
          shell: bash
          env:
              VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
              VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}
          run: |
              if [ "${{ inputs.environment }}" = "production" ]; then
                  vercel pull --environment=production --token=${{ inputs.vercel-token }}
              else
                  vercel pull --environment=preview --token=${{ inputs.vercel-token }}
              fi

        - name: Build project locally
          shell: bash
          env:
              BUILD_ARGS: ${{ inputs.build-args }}
          run: |
              if [ -n "$BUILD_ARGS" ]; then
                  vercel build $BUILD_ARGS
              else
                  vercel build
              fi

        - name: Deploy prebuilt project to Vercel
          id: deploy
          shell: bash
          run: |
              if [ -n "${{ inputs.deploy-args }}" ]; then
                  URL=$(vercel deploy --prebuilt ${{ inputs.deploy-args }} --token=${{ inputs.vercel-token }})
              else
                  URL=$(vercel deploy --prebuilt --token=${{ inputs.vercel-token }})
              fi
              echo "url=$URL" >> $GITHUB_OUTPUT
