name: Quality

description: 'Runs build, lint, and test checks to ensure code quality'

runs:
    using: 'composite'
    steps:
        - name: Build
          shell: bash
          run: |
              set -e
              npm run build

        - name: Lint
          shell: bash
          run: |
              set -e
              npm run lint

        - name: Test
          shell: bash
          run: |
              set -e
              npm run test
