name: Prepare environment

description: 'Sets up Node.js environment and installs dependencies with caching'

inputs:
    repo-token:
        description: 'Token to access the repo'
        required: true

runs:
    using: 'composite'
    steps:
        - uses: actions/setup-node@v6
          with:
              node-version: 24
              cache: 'npm'

        - name: Restore install outputs from cache
          id: cache-install
          uses: actions/cache/restore@v5
          with:
              path: |
                  **/node_modules/**
                  **/generated/**
              key: ${{ runner.os }}-install-${{ github.sha }}

        - name: Install Packages
          if: steps.cache-install.outputs.cache-hit != 'true'
          shell: bash
          run: npm ci
          env:
              CI: true

        - name: Save install output to cache
          uses: actions/cache/save@v5
          if: steps.cache-install.outputs.cache-hit != 'true'
          with:
              path: |
                  **/node_modules/**
                  **/generated/**
              key: ${{ runner.os }}-install-${{ github.sha }}
