name: Prepare environment

inputs:
    repo-token:
        description: 'Token to access the repo'
        required: true

runs:
    using: 'composite'
    steps:
        - uses: actions/setup-node@v6
          with:
              node-version: 22
              cache: 'npm'

        - name: Install Packages
          shell: bash
          run: npm ci
          env:
              CI: true
