name: Prepare environment

description: 'Sets up Node.js environment and installs dependencies with caching'

inputs:
    repo-token:
        description: 'Token to access the repo'
        required: true

runs:
    using: 'composite'
    steps:
        - uses: actions/setup-node@v6
          with:
              node-version: 24
              cache: 'npm'

        - name: Restore node_modules from cache
          id: cache-node-modules
          uses: actions/cache/restore@v4
          with:
              path: |
                  node_modules
                  **/node_modules
              key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                  ${{ runner.os }}-node-modules-

        - name: Install Packages
          shell: bash
          run: |
              set -e
              # npm ci will be faster if node_modules exists from cache
              # It will still verify integrity and install any missing packages
              npm ci
          env:
              CI: true

        - name: Save node_modules to cache
          uses: actions/cache/save@v4
          if: always()
          with:
              path: |
                  node_modules
                  **/node_modules
              key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
