name: Build preview

description: 'Builds and deploys a preview environment to Vercel'

inputs:
    vercel-token:
        description: 'Token to access Vercel'
        required: true
    github-token:
        description: 'Token to access GitHub (for PR comments)'
        required: true
    vercel-org-id:
        description: 'Vercel organization ID'
        required: true
    vercel-project-id:
        description: 'Vercel project ID to deploy'
        required: true
    vercel-project-name:
        description: 'Vercel project name to deploy'
        required: true

runs:
    using: "composite"
    steps:
        - name: Install Vercel CLI
          shell: bash
          run: |
              set -e
              npm i --global vercel

        - name: Pull environment variables from Vercel
          shell: bash
          run: |
              set -e
              vercel pull --environment=preview --token=${{ inputs.vercel-token }}

        - name: Build project locally
          shell: bash
          run: |
              set -e
              vercel build

        - name: Deploy prebuilt project to Vercel
          shell: bash
          run: |
              set -e
              vercel deploy --prebuilt --token=${{ inputs.vercel-token }}
